language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8
- pypy3
before_script:
- pip install pyflakes cram python-coveralls codecov
script:
- pyflakes *.py src/ffind/*.py
- python setup.py install
- ffind --ignore-vcs . '(?<!argparse).py$' --exec=pyflakes
- make travis
- codecov
after_success:
- coveralls
deploy:
  provider: pypi
  user: jaimebuelta
  password:
    secure: H0ZVmNzwxD18mB5kglqnUHhejqqHHRoRLvWwpW8/oSIrU7JspzGTJthxQGk8ZlX/CZCQGSySPDF3IGxaal2CzQRADC6NO/tSr4E3dSOyQ44k7ZXttwylNKLKVfoDsAcru73hWbG5DHLWiVJ8PGyjUHw5bwDQjl8Dz96QzCUBfmrNE/bmRLF2Uq5ey6cjA4L2GuGeKneZlI7pVQU2WMLzcf3BGKJCpn/2nEkP4YFGbMITrboRknYlutyt7EAHiSKaU2bT56ZP0VSzlI8IL4K89w4EA+G1vVtefWIFKRkQPR69gHVMOGqp7YhSw7NrpkNc5KH4xmeht8xbyplT8Cx1315IBA1G/zcfEwTalRf/ABdrLWqo6xDi2w+66pC5ILDJezV1iCzF+S0b6j5nGX599CINMQnjVYFvUT7NpHbMpewV9kY3owsswRzglvgygF+7UQObaphgE24714fzrN07r7ISwbHtrmlcPlzfaGulHgyj1ZeuHFdmjI5KOfRN635WBoN00Zgbakd07ER91daTLiQ4nS2QKfhyQWOoLMHFZSSmH4KOmwPkeqgt5gzIgCA50wUcGgMB7TGoZAkCx0tcqPFESr6nxmIQq3ZB79kOs3B6IS2lIqFDP/uhUbFCB2sc9fwjF+PKLkpE+HQIx1d+uJ44IcgnoND/LQ+45wSRFP0=
  skip_existing: true
  distributions: "sdist bdist_wheel"
  on:
    tags: true
