language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
before_script:
  - pip install pyflakes cram python-coveralls
script:
  - pyflakes *.py ffind/*.py
  - python setup.py install
  - ffind --ignore-vcs . '(?<!argparse).py$' --exec=pyflakes
  - make travis
after_success:
  - coveralls
